spring:
  application:
    name: mdd-api
  jpa:
    properties:
      hibernate:
        globally_quoted_identifiers: true
  docker:
    compose:
      file: compose.yml

app:
  auth:
    jwt-secret: ${JWT_SECRET}
    access-token-ttl-seconds: 900
    refresh-token-ttl-days: 1
    refresh-cookie-name: refreshToken
    cookie-secure: false
    cookie-same-site: Strict
    cookie-path: /
  cors:
    allowed-origins: 
      - http://localhost:4200
